import type { CommandRegistry } from '../types'
import { EMAIL, RESUME_FILENAME } from './contact'

export const KONAMI_SEQUENCE = [
  'ArrowUp', 'ArrowUp', 'ArrowDown', 'ArrowDown',
  'ArrowLeft', 'ArrowRight', 'ArrowLeft', 'ArrowRight',
  'b', 'a',
] as const

export const TERMINAL_INTRO: string[] = [
  '> SYSTEM ACCESS GRANTED',
  '> Loading profile: priyank.bardolia ...',
  '',
  '  Welcome to the other side.',
  '  Type "help" to see what\'s here.',
  '',
]

export const COMMANDS: CommandRegistry = {
  help: [
    '',
    '  Available commands:',
    '',
    '  help          you\'re looking at it',
    '  whoami        the short version',
    '  skills        what I work with',
    '  story         how it started',
    '  resume        download my resume',
    '  hire          you know you want to',
    '  secret        if you dare',
    '  clear         wipe the terminal',
    '  exit          close this window',
    '',
  ],
  whoami: [
    '',
    '  Full-stack engineer. Seattle.',
    '  Shipped real systems at GE Healthcare — now building',
    '  AI-first products independently on the side.',
    '  RAG, agents, and the boring infra that keeps them honest.',
    '',
  ],
  skills: [
    '',
    '  Primary      TypeScript ██████████████  React ██████████████',
    '               Next.js ██████████████   Python ██████████████',
    '',
    '  Backend      Node.js ██████████████   FastAPI ██████████████',
    '               PostgreSQL ██████████████',
    '',
    '  AI / LLM     RAG ██████████████        LLM Integration ██████████████',
    '               AI Agents ██████████████   Prompt Engineering ██████████████',
    '',
    '  Infra        AWS ██████████████        Docker ██████████████',
    '               Vercel / Serverless ██████████████',
    '',
    '  Also:        Prisma, Supabase, Streaming LLMs,',
    '               Multi-tenant Architecture, Reliability Engineering',
    '',
  ],
  story: [
    '',
    '  Age 16: wrote a Python script that scraped cricket scores.',
    '  It broke every other week. I loved it.',
    '',
    '  Built my first real app at Cepheid — C# .NET, 10K users.',
    '  Then Scale AI — teaching LLMs to code better than me.',
    '  Then GE Healthcare — processing billions of events.',
    '  Now independent — building API Sentinel + AI products.',
    '',
    '  The pattern: find a hard problem, build the ugly v1,',
    '  then polish it until it feels inevitable.',
    '',
    '  This portfolio? Lost count of the versions.',
    '',
  ],
  resume: [
    '',
    '  > Preparing download...',
    `  ✓ ${RESUME_FILENAME} — done.`,
    '',
  ],
  hire: [
    '',
    '  > sudo hire priyank --force',
    '',
    '  ✓ Email copied to clipboard.',
    '  ✓ Your future just got better.',
    '',
    `  ${EMAIL}`,
    '',
  ],
  secret: [
    '',
    '  Runs on coffee and the fear of stale PRs.',
    '',
    '  Rewrites his own code 3-4 times before pushing.',
    '  The first version exists to find out what the',
    '  problem actually is.',
    '',
    '  Would rather ship a small honest thing than',
    '  a big fake one.',
    '',
    '  Thinks most TODO comments are lies.',
    '  Thinks most abstractions are someone losing a fight',
    '  with their last self.',
    '',
    '  Big finance geek. Loves the unit economics, margins,',
    '  and cash flow that quietly run a company in the',
    '  background — the real story behind the product.',
    '',
    '  If you found this, you\'re the kind of person',
    '  I want to work with.',
    '',
  ],
}

export const HIRE_ALIASES = ['hire', 'sudo hire priyank', 'sudo hire priyank --force'] as const

export const unknownCommand = (cmd: string): string[] => [
  '',
  `  command not found: ${cmd}`,
  '  Type "help" for available commands.',
  '',
]
