export * from './experience'
export * from './projects'
export * from './about'
export * from './contact'
export * from './hero'
export * from './nav'
export * from './marquee'
export * from './easterEgg'
