#!/usr/bin/env node
/**
 * Build-time PDF text extractor.
 *
 * Reads public/resume.pdf, extracts the text content, and writes it to
 * src/content/_resumeText.ts as a single exported string constant.
 *
 * Runs automatically before each build via the `prebuild` npm script.
 * Run manually after updating the PDF:
 *
 *     node scripts/extract-resume.mjs
 *
 * Output file is intentionally prefixed with `_` so future-you knows
 * it is generated — don't edit it by hand.
 */

import { readFile, writeFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'
import { getDocument } from 'pdfjs-dist/legacy/build/pdf.mjs'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = join(__dirname, '..')
const PDF_PATH = join(ROOT, 'public', 'resume.pdf')
const OUT_PATH = join(ROOT, 'src', 'content', '_resumeText.ts')

async function extractText() {
  const data = new Uint8Array(await readFile(PDF_PATH))
  const pdf = await getDocument({ data, useSystemFonts: true }).promise

  const pages = []
  for (let i = 1; i <= pdf.numPages; i++) {
    const page = await pdf.getPage(i)
    const content = await page.getTextContent()

    // Each `item` is a text fragment with its own position.
    // Join with spaces; collapse runs of whitespace at the end.
    const text = content.items
      .map((item) => ('str' in item ? item.str : ''))
      .join(' ')

    pages.push(text)
  }

  return pages
    .join('\n\n')
    .replace(/[ \t]+/g, ' ')
    .replace(/\n{3,}/g, '\n\n')
    .trim()
}

function toTsString(raw) {
  // Backticks escape only `, $, and \ — much cleaner than single-quote escaping.
  const escaped = raw.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$/g, '\\$')
  return `// AUTO-GENERATED by scripts/extract-resume.mjs — do not edit by hand.
// Source: public/resume.pdf
// Re-run \`npm run extract:resume\` after updating the PDF.

export const RESUME_TEXT = \`${escaped}\`
`
}

async function main() {
  console.log(`Reading ${PDF_PATH}…`)
  const text = await extractText()
  console.log(`Extracted ${text.length} characters from PDF.`)

  await writeFile(OUT_PATH, toTsString(text), 'utf8')
  console.log(`Wrote ${OUT_PATH}`)
}

main().catch((err) => {
  console.error('Resume extraction failed:', err)
  process.exit(1)
})
